### ISSUE TITLE
Fork Permission

### ISSUE THREAD

**Issue by Subw343** [streaak/keyhacks#117]
Hello@streaak,
 
I was recently learning about information disclosure on Bug hunting and fortunately for me, I landed on this repo https://github.com/streaak/keyhacks which I find very useful to learn from. Going straight forward to the point, I would like to seek your permission in forking this repo for research purpose. Will be glad if permission is granted.

Kind regards!
@Subw343

**Comment by evanstucker-hates-2fa** [comment]
You don't need permission to fork a repo. Just click the Fork button at the top-right side of the repo.
