### ISSUE TITLE
Add Giphy API key

### ISSUE THREAD

**Issue by Devang-Solanki** [streaak/keyhacks#129]
Hi @streaak can you please add Giphy API key.

To verify api key we can simply request or visit in browser.

`https://api.giphy.com/v1/gifs/trending?api_key=<YOUR KEY>` 

if it gives 200 then it means key is active and correct if it is wrong it will give you 401 unauthorized error.

**Comment by l1unter** [comment]
will, does that has a real impact, i mean should a bug hunter report it??

**Comment by Devang-Solanki** [comment]
I don't think this will help any bug bounty hunters

**Comment by streaak** [comment]
Closing as it has no actual impact
