### ISSUE TITLE
Datadog

### ISSUE THREAD

**Issue by hakluke** [streaak/keyhacks#16]
Format:
```
Application key: [0-9a-z]{40}
API key: [0-9a-z]{32}
```

Test:
https://api.datadoghq.com/api/v1/dashboard?api_key=<api_key>&application_key=<application_key>

**Comment by codingo** [comment]
Hi @hakluke, will be actioning this one tomorrow morning. Thank-you for the input!

**Comment by streaak** [comment]
Thanks @hakluke and @codingo. Just added this.
