### ISSUE TITLE
Add Github SSH Keys

### ISSUE THREAD

**Issue by ajxchapman** [streaak/keyhacks#2]
SSH private keys can be tested against `github.com` to see if they are registered against an existing user account. If the key exists the username corresponding to the key will be provided:
```sh
$ ssh -i <path to SSH private key> -T git@github.com
Hi <username>! You've successfully authenticated, but GitHub does not provide shell access.
```

**Comment by EdOverflow** [comment]
Thank you for your contribution, @ajxchapman.

**Comment by zzeitlin** [comment]
The same is true for `gitlab.com`:
```bash
ssh -i <path to SSH private key> -T git@gitlab.com
Welcome to GitLab, <username>!
```
