### ISSUE TITLE
Google Cloud Messaging (GCM)

### ISSUE THREAD

**Issue by benichmt1** [streaak/keyhacks#22]
It looks like GCM is deprecated, but they are still good for another few days :man_shrugging: 

URL:
https://developers.google.com/cloud-messaging/

Request:
```curl -s -X POST --header "Authorization: key=AI..." --header "Content-Type:application/json" 'https://gcm-http.googleapis.com/gcm/send' -d '{"registration_ids":["1"]}' ```

**Comment by ankushgoel27** [comment]
it's deprecated. Any other way to test the API key?
