### ISSUE TITLE
Tool to check creds automatically

### ISSUE THREAD

**Issue by Metnew** [streaak/keyhacks#28]
Hey, it's a great project! 
It could be even better if it'd be possible to check creds from the shell.
Writing a tool is easy, but it requires mirroring current README (or only API URLs) into JSON or similar format.

This project includes only API urls and probably won't be used as a seed for any tools.

Example json:
```
{
   "service": "AWS",
   "description": "Checks AWS keys via IAM API",
   "url": "https://aws/url",
   "expected_status": "200",
   "expected_body?": "{\"key\":\"is_valid\"}"
}
```

**Comment by codingo** [comment]
Watch this space, there's a couple I know of in the works already but not likely to be released until Defcon.
