### ISSUE TITLE
Add Google maps API key

### ISSUE THREAD

**Issue by yassineaboukir** [streaak/keyhacks#3]
Google maps API key should be restricted to certain projects. I quote

> Restrict your API keys to be used by only the IP addresses, referrer URLs, and mobile apps that need them: By restricting the IP addresses, referrer URLs, and mobile apps that can use each key, you can reduce the impact of a compromised API key. You can specify the hosts and apps that can use each key from the GCP Console Credentials page and then create a new API key with the settings you want, or edit the settings of an existing API key.

_Source: https://support.google.com/googleapi/answer/6310037?hl=en_

You can test the API key is valid and not restricted using:

> https://maps.googleapis.com/maps/api/directions/json?origin=Toronto&destination=Montreal&key=KEY_HERE

If properly restricted, it should return:

> "This API project is not authorized to use this API."

Otherwise, it will return proper JSON data with directions and geo coordinates.

**Comment by streaak** [comment]
Hey, thank you for sending this in.
I've added Google Maps API key in [this commit](https://github.com/streaak/keyhacks/commit/1848eff377d6f4ea3eed6786f783d9f41dbc3683)
