### ISSUE TITLE
Paypal client id and secret key

### ISSUE THREAD

**Issue by Quikko** [streaak/keyhacks#34]
**Paypal's access token**:
* https://developer.paypal.com/docs/api/get-an-access-token-curl/ :

```
curl -v https://api.sandbox.paypal.com/v1/oauth2/token \
   -H "Accept: application/json" \
   -H "Accept-Language: en_US" \
   -u "client_id:secret" \
   -d "grant_type=client_credentials"
```

Access token can be further used to extract data from the PayPal API. More information:

* https://developer.paypal.com/docs/api/overview/#make-rest-api-calls

**Comment by codingo** [comment]
Thank-you for this, aiming to add tomorrow.

**Comment by streaak** [comment]
Thanks @codingo and @Quikko
