### ISSUE TITLE
Scripted tests

### ISSUE THREAD

**Issue by gwen001** [streaak/keyhacks#46]
Hi,

Based on your work in this repo, I wrote a small bash script in order to make our life easier and save our precious time :)

Here it is:
https://github.com/gwen001/pentest-tools/blob/master/testkeys.sh

I don't have valid and invalid keys for all services (and it's alot of copy/paste xD) so feel free to ping me if something goes wrong.

Thank you :)

**Comment by gwen001** [comment]
Let's rename it to fit your repo's name :)

https://github.com/gwen001/pentest-tools/blob/master/keyhacks.sh

**Comment by streaak** [comment]
Hey @gwen001,
Thanks you for this. I will add it to the original repository after review hopefully by this weekend.

**Comment by gwen001** [comment]
No problem, let me know if I can help to test :)
