### ISSUE TITLE
Add FreshDesk API

### ISSUE THREAD

**Issue by JvdHout1011** [streaak/keyhacks#61]
Hi, 

Easy way to check if found Freshdesk API keys are valid: 

curl -v -u user@yourcompany.com:test -X GET 'https://domain.freshdesk.com/api/v2/groups/1'
--

This requires the API key in 'user@yourcompany.com', pass in 'test' and 'domain.freshdesk.com' to be the instance url of the target. In case you get a 403, try the endpoint api/v2/tickets, which is accessible for all keys.

**Comment by streaak** [comment]
Thank you.
