### ISSUE TITLE
how to use google captcha 

### ISSUE THREAD

**Issue by balook** [streaak/keyhacks#64]
pls provide require info im trying this but giving invalidkeys 

https://www.google.com/recaptcha/api/siteverify?secret=your_secret&response=response_string&remoteip=user_ip_address

**Comment by streaak** [comment]
Hey @balook , 
Google Recaptcha key verification methods are present [here](https://github.com/streaak/keyhacks#Google-Recaptcha-key). A potential reason why it could be giving invalid keys is mentioned [here](https://stackoverflow.com/questions/44700739/recaptcha-error-code-invalid-keys). If you find another method, do let me know.
