### ISSUE TITLE
Add ipstack API

### ISSUE THREAD

**Issue by blkout08** [streaak/keyhacks#69]
Geo location

`curl https://api.ipstack.com/{ip_address}?access_key={keyhere}`

Documentation: https://ipstack.com/documentation
Pricing: https://ipstack.com/product

Free tier only up to 10K requests per month.

**Comment by streaak** [comment]
Hey @blkout08 
Could you make a PR for this?
Thanks.

**Comment by blkout08** [comment]
https://github.com/streaak/keyhacks/pull/70

Done (i think)

**Comment by streaak** [comment]
Awesome, thank you. Closing this now.
