### ISSUE TITLE
JumpCloud

### ISSUE THREAD

**Issue by abdilahrf** [streaak/keyhacks#77]
Based on this report https://hackerone.com/reports/716292
there is an other endpoint to validate & increasing the severity of the found keys

curl -H "x-api-key: █" "https://console.jumpcloud.com/api/systemusers"
curl -H "x-api-key: █" "https://console.jumpcloud.com/api/applications"
curl -H "x-api-key: █" "https://console.jumpcloud.com/api/systems"

**Comment by streaak** [comment]
Hey @abdilahrf 
Could you create a PR for the same?
