### ISSUE TITLE
Add Mapbox secret token

### ISSUE THREAD

**Issue by shelld3v** [streaak/keyhacks#79]
Mapbox secret token (super confidential) is something that looked like this: `sk.eyJ...`. You should add it into your content. Also, there is also a Mapbox public token, looked like this: `pk.eyJ...` which does not confidential at all, it supposed to be public. 

Secret access token started with 'sk.' (**s**ecret **k**ey)
Public access token started with 'pk.' (**p**ublic **k**ey)
*Mapbox*

**Comment by streaak** [comment]
Hey @shelld3v 
We already have Mapbox tokens [here](https://github.com/streaak/keyhacks#mapbox-api-key). If you can add more info to it, please create a PR

**Comment by shelld3v** [comment]
At the time I created this issue, there wasn't that token
