### ISSUE TITLE
MailChimp

### ISSUE THREAD

**Issue by gwen001** [streaak/keyhacks#8]
Format:
```
[0-9a-z]{32}-[0-9a-z]{2,5}
```

Test:
```
curl --request GET --url 'https://<dc>.api.mailchimp.com/3.0/' --user 'anystring:<API_KEY>' --include
```

Where `<dc>` is the second part of the key, after the '-'.

**Comment by codingo** [comment]
Another great submission. Same as #9, I'll aim to look into this tomorrow.

Thank-you.

**Comment by streaak** [comment]
Hey, thanks for sending this in. I have just added this to the repo.
