### ISSUE TITLE
Razorpay API key issue

### ISSUE THREAD

**Issue by welltest** [streaak/keyhacks#99]
@streaak  What I am missing? 

![2021-05-24 20_43_26-root@kali_ ~](https://user-images.githubusercontent.com/7748482/119368831-1d424080-bcd1-11eb-8660-416985f0a709.png)

**Comment by w1th0ut** [comment]
Because that format for in shell file, example like this:
```shell
curl -u <YOUR_KEY_ID>:<YOUR_KEY_SECRET> \
  https://api.razorpay.com/v1/payments
```

If running on immediately on terminal, run like this:
```
curl -u <YOUR_KEY_ID>:<YOUR_KEY_SECRET> https://api.razorpay.com/v1/payments
```
